'use client';
import {useEffect,useState} from 'react';
import {Star,ArrowRight,ArrowLeft,Check,Sparkles,ShieldCheck,MapPin,RefreshCw} from 'lucide-react';
import Brand from './brand';
import GoogleReviewHandoff from './google-review-handoff';
import {restaurants,track} from '@/lib/demo-store';
import {experienceTags} from '@/lib/review';
import type {Restaurant,ReviewStyle} from '@/lib/types';
export default function ReviewFlow({slug}:{slug:string}){
 const [restaurant,setRestaurant]=useState<Restaurant|null|undefined>(undefined),[step,setStep]=useState(1),[rating,setRating]=useState(0),[tags,setTags]=useState<string[]>([]),[comment,setComment]=useState(''),[draft,setDraft]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[approved,setApproved]=useState(false),[style,setStyle]=useState<ReviewStyle>('natural'),[edited,setEdited]=useState(false),[confirmRewrite,setConfirmRewrite]=useState(false);
 useEffect(()=>{void fetch('/api/restaurants/'+encodeURIComponent(slug)).then(async response=>{const data=await response.json() as {restaurant?:Restaurant;error?:string};if(!response.ok){setRestaurant(null);return;}const r=data.restaurant!;setRestaurant(r);try{const key='tabletap-visit-'+r.id;if(!sessionStorage.getItem(key)){track(r.id,'scan');sessionStorage.setItem(key,'1');}}catch{}}).catch(()=>{setRestaurant(null);setError('Could not load this restaurant. Please refresh.');});try{const saved=JSON.parse(sessionStorage.getItem('tabletap-draft-'+slug)||'null');if(saved&&saved.expires>Date.now()&&typeof saved.draft==='string'&&saved.rating>=1&&saved.rating<=5&&Array.isArray(saved.tags)){setRating(saved.rating);setTags(saved.tags);setComment(saved.comment||'');setDraft(saved.draft);setStyle(saved.style||'natural');setStep(3);setApproved(false);}}catch{}},[slug]);
 async function generate(){if(!restaurant)return;setBusy(true);setError('');try{const res=await fetch('/api/review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rating,tags,comment,restaurantName:restaurant.name,style,previousDraft:draft})});const data=await res.json() as {draft:string;error?:string};if(!res.ok)throw Error(data.error||'Please try again.');setDraft(data.draft);setStep(3);setApproved(false);setEdited(false);setConfirmRewrite(false);track(restaurant.id,'draft',{rating,tags});}catch(e){setError(e instanceof Error?e.message:'We could not create your draft. Please try again.');}finally{setBusy(false);}}
 function saveBeforeLeaving(){try{sessionStorage.setItem('tabletap-draft-'+slug,JSON.stringify({draft,rating,tags,comment,style,expires:Date.now()+30*60*1000}));}catch{}}
 return <div className="review-page"><header className="review-header"><Brand/><span>YOUR EXPERIENCE MATTERS</span></header><main className="review-shell">{restaurant===undefined?<div className="review-card"><p>Getting your table ready…</p></div>:!restaurant||!restaurant.active?<div className="review-card unavailable"><ShieldCheck size={36}/><h1>{restaurant?'This review page is paused.':'We couldn’t find that table.'}</h1><p>{restaurant?'Please ask the restaurant for its current review link.':'Check the QR link with the restaurant. The restaurant may have paused or changed its review page.'}</p></div>:<><section className="restaurant-banner"><div className="cafe-photo"/><div className="banner-shade"/><div className="restaurant-banner-content"><span className="venue-type">{restaurant.category}</span><h2>{restaurant.name}</h2>{restaurant.location&&<span><MapPin size={14}/>{restaurant.location}</span>}</div><div className="venue-logo" style={{background:restaurant.color}}>{restaurant.initials}</div></section><section className="review-card"><div className="stepper" aria-label={'Step '+step+' of 3'}>{['Your visit','The details','Your words'].map((s,i)=><div key={s} className={step>=i+1?'complete':''}><span>{step>i+1?<Check size={13}/>:i+1}</span>{s}</div>)}</div>
 {step===1&&<div className="review-step"><div className="eyebrow">A MOMENT TO REFLECT</div><h1>How was your visit?</h1><p>The little things matter.<br/>Tell us how it felt, honestly.</p><div className="stars" role="group" aria-label="Rate your experience">{[1,2,3,4,5].map(n=><button key={n} aria-label={`${n} star${n>1?'s':''}`} aria-pressed={rating===n} className={rating>=n?'filled':''} onClick={()=>setRating(n)}><Star strokeWidth={1.4}/></button>)}</div><div className="rating-caption" aria-live="polite">{['Tap a star to get started','Disappointing','Could be better','It was okay','Really good','Loved it'][rating]}</div><button className="btn primary full" disabled={!rating} onClick={()=>setStep(2)}>A few details <ArrowRight size={18}/></button><p className="review-footnote">Every experience is welcome. No signup needed.</p></div>}
 {step===2&&<div className="review-step"><button className="text-link back" onClick={()=>setStep(1)}><ArrowLeft size={15}/> Your rating</button><h1>What stood out?</h1><p>Choose what matches your experience.<br/>The good, the not-so-good, or both.</p><div className="tags">{experienceTags.map(t=><button key={t} aria-pressed={tags.includes(t)} className={tags.includes(t)?'chosen':''} onClick={()=>setTags(tags.includes(t)?tags.filter(x=>x!==t):[...tags,t])}>{tags.includes(t)&&<Check size={14}/>} {t}</button>)}</div><label className="comment-label" htmlFor="comment">Anything else? <span>Optional</span></label><textarea id="comment" value={comment} maxLength={500} onChange={e=>setComment(e.target.value)} placeholder="A dish you tried, a moment you remember…" rows={3}/><div className="char-count">{comment.length}/500</div><button className="btn primary full" disabled={busy} onClick={generate}><Sparkles size={18}/>{busy?'Finding your words…':'Help me write my review'}<ArrowRight size={18}/></button><p className="review-footnote">Only your experiences. No made-up details.</p></div>}
 {step===3&&<div className="review-step"><button className="text-link back" onClick={()=>setStep(2)}><ArrowLeft size={15}/> Change details</button><div className="draft-title"><h1>Your visit. Your words.</h1><span className="draft-stars">{'★'.repeat(rating)}</span></div><p>A starting point for your review.<br/>Make it sound like you.</p><label className="sr-only" htmlFor="draft">Edit your review</label><textarea id="draft" className="draft-text" rows={6} maxLength={2000} value={draft} onChange={e=>{setDraft(e.target.value);setEdited(true);setApproved(false);}}/><div className="draft-meta"><span><Sparkles size={13}/> Writing assistant · demo</span><span>{draft.length}/2000</span></div><div className="rewrite-controls"><label htmlFor="review-style">Writing style</label><select id="review-style" value={style} disabled={busy} onChange={e=>setStyle(e.target.value as ReviewStyle)}><option value="natural">Natural</option><option value="short">Short & simple</option><option value="detailed">More detail</option></select><button className="text-link" disabled={busy} onClick={()=>{if(edited)setConfirmRewrite(true);else void generate();}}><RefreshCw size={15} className={busy?'spinning':''}/>{busy?'Writing another version…':'Try another version'}</button></div>{confirmRewrite&&<div className="rewrite-confirm"><p>Replace your edits with a new draft?</p><button className="text-link" onClick={()=>void generate()} disabled={busy}>Write a new version</button><button className="text-link" onClick={()=>setConfirmRewrite(false)}>Keep my edits</button></div>}<label className="approval"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/><span>This reflects my actual experience.</span></label><GoogleReviewHandoff restaurant={restaurant} draft={draft} rating={rating} approved={approved} disabled={busy} beforeLeave={saveBeforeLeaving}/></div>}
 {error&&<div role="alert" className="error">{error}</div>}</section><div className="review-trust"><ShieldCheck size={15}/> Genuine feedback. A little easier.</div></>}</main><footer className="review-footer">Powered by <b>tabletap.</b><span>Small taps. Real voices.</span></footer></div>;
}
